# Generated by Django 3.1.2 on 2020-11-24 02:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20201110_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(default=datetime.datetime(2020, 11, 24, 2, 21, 19, 622939, tzinfo=utc)),
        ),
    ]
