# Generated by Django 3.1.2 on 2020-11-24 03:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_auto_20201123_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='num_reviews',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(default=datetime.datetime(2020, 11, 24, 3, 54, 40, 910336, tzinfo=utc)),
        ),
    ]
