# Generated by Django 3.1.2 on 2020-12-01 15:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_auto_20201130_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(default=datetime.datetime(2020, 12, 1, 15, 34, 52, 369183, tzinfo=utc)),
        ),
    ]
