# Generated by Django 3.1.2 on 2020-12-14 05:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_auto_20201212_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(default=datetime.datetime(2020, 12, 14, 5, 5, 8, 395395, tzinfo=utc)),
        ),
    ]
