# Generated by Django 3.1.2 on 2020-12-14 20:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_auto_20201214_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(default=datetime.datetime(2020, 12, 14, 20, 3, 14, 823575, tzinfo=utc)),
        ),
    ]
